### ISSUE TITLE
[1.18.2] Server Crash

### ISSUE THREAD

**Issue by DaDiGui** [yuuki14202028/thirst#2]
https://mclo.gs/sljojgt

**Comment by yuuki14202028** [comment]
Have you implemented https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge?

**Comment by DaDiGui** [comment]
yes, of course! In singleplayer works fine

**Comment by yuuki14202028** [comment]
The thirst-0.2.2.jar is for Minecraft version 1.19 only; 1.18.2 is thirst-0.2.1.jar.
Also, the ModList in CrashLog does not include KotlinForForge, so please check again.

**Comment by yuuki14202028** [comment]
Closed by mistake.
