### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by ZekePolarisBSH** [yuuki14202028/thirst#5]
Please tell me if I am using this wrong or not. It did not give me any thirst bar and I am not getting thirsty on the game...

**Comment by yuuki14202028** [comment]
Have you installed "Kotlin for Forge"?
This mod is working in my environment.

**Comment by ZekePolarisBSH** [comment]
Sorry late reply. I am using Fabric. Also there was a hack that happened
with Forge. And I am sure that I clicked on Fabric.

**Comment by yuuki14202028** [comment]
This mod is Forge mod.
Please using Forge.
